"""Recipe data models for the Recipe Agent."""

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class RecipeType(str, Enum):
    """Types of recipes the agent can generate."""

    COCKTAIL = "cocktail"
    FOOD = "food"
    DESSERT = "dessert"


class Ingredient(BaseModel):
    """Individual ingredient with quantity information."""

    model_config = ConfigDict(str_strip_whitespace=True)

    name: str = Field(..., description="Ingredient name")
    quantity: str = Field(..., description="Amount (e.g., '2', '1/2')")
    unit: str | None = Field(default=None, description="Measurement unit (e.g., 'oz', 'cups', 'grams', 'ml')")
    notes: str | None = Field(default=None, description="Preparation notes (e.g., 'diced', 'chilled')")

    @field_validator("name", "quantity")
    @classmethod
    def _strip_required(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("must be provided")
        return cleaned

    @field_validator("unit", "notes")
    @classmethod
    def _strip_optional(cls, value: str | None) -> str | None:
        return value.strip() or None if value else None


class Recipe(BaseModel):
    """Structured recipe output generated by the agent (DB-friendly types)."""

    model_config = ConfigDict(str_strip_whitespace=True)

    name: str = Field(..., description="Recipe name")
    recipe_type: RecipeType = Field(..., description="Type of recipe")
    ingredients: list[Ingredient] = Field(..., description="List of ingredients")
    instructions: list[str] = Field(..., description="Ordered preparation steps")
    prep_time_minutes: int | None = Field(default=None, ge=0, description="Preparation time in minutes")
    cook_time_minutes: int | None = Field(default=None, ge=0, description="Cooking time in minutes (for food)")
    servings: int | None = Field(default=None, ge=1, description="Number of servings")
    source_references: list[str] = Field(default_factory=list, description="Source URLs")
    notes: str | None = Field(default=None, max_length=2000, description="Tips or variations")
    user_notes: str | None = Field(default=None, max_length=2000, description="User-added notes")
    tags: list[str] = Field(default_factory=list, description="User-defined tags")
    conversation_id: str | None = Field(default=None, max_length=100, description="Conversation reference")

    @field_validator("name")
    @classmethod
    def _strip_name(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("name is required")
        return cleaned

    @field_validator("instructions")
    @classmethod
    def _clean_instructions(cls, steps: list[str]) -> list[str]:
        cleaned = [step.strip() for step in steps if isinstance(step, str)]
        if any(not step for step in cleaned):
            raise ValueError("instructions cannot be empty strings")
        return cleaned

    @field_validator("source_references", "tags")
    @classmethod
    def _strip_list(cls, values: list[str]) -> list[str]:
        return [v.strip() for v in values if isinstance(v, str) and v.strip()]

    @model_validator(mode="after")
    def _check_lists(self) -> "Recipe":
        if not self.ingredients:
            raise ValueError("at least one ingredient is required")
        if not self.instructions:
            raise ValueError("at least one instruction step is required")
        return self

    def to_db_dict(self) -> dict:
        """Return a DB-ready dict with primitive types."""
        data = self.model_dump(mode="python")
        data["recipe_type"] = self.recipe_type.value
        return data

