"""Recipe data models for the Recipe Agent."""

from datetime import timedelta
from enum import Enum

from pydantic import BaseModel, Field


class RecipeType(str, Enum):
    """Types of recipes the agent can generate."""

    COCKTAIL = "cocktail"
    FOOD = "food"
    DESSERT = "dessert"


class Ingredient(BaseModel):
    """Individual ingredient with quantity information."""

    name: str = Field(..., description="Ingredient name")
    quantity: str = Field(..., description="Amount (e.g., '2', '1/2')")
    unit: str | None = Field(default=None, description="Measurement unit (e.g., 'oz', 'cups', 'grams', 'ml')")
    notes: str | None = Field(default=None, description="Preparation notes (e.g., 'diced', 'chilled')")


class Recipe(BaseModel):
    """Structured recipe output generated by the agent."""

    name: str = Field(..., description="Recipe name")
    recipe_type: RecipeType = Field(..., description="Type of recipe")
    ingredients: list[Ingredient] = Field(..., description="List of ingredients")
    instructions: list[str] = Field(..., description="Ordered preparation steps")
    prep_time: timedelta | None = Field(default=None, description="Preparation time")
    cook_time: timedelta | None = Field(default=None, description="Cooking time (for food)")
    servings: int | None = Field(default=None, description="Number of servings")
    source_references: list[str] = Field(default_factory=list, description="Source URLs")
    notes: str | None = Field(default=None, description="Tips or variations")

